### ISSUE TITLE
request for EMNLP 2023 data

### ISSUE THREAD

**Issue by tnlin** [papercopilot/paperlists#1]
Hi,  

Thank you for your amazing work, the data is extremely helpful for analyzing and tracking the research trend.

It would be great if the repo could share the data about EMNLP 2023, which is available on the website already.

Thanks !

**Comment by jingyangcarl** [comment]
check this out: https://raw.githubusercontent.com/Papercopilot/paperlists/main/emnlp/emnlp2023.json
